#+title: Daily work log for Anshuman Karthik R

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Today was about familiarizing ourselves with shell commands, version control and Emacs. 
   + What did I get done against each task?
   I installed softwares and packages to set up our laptops. This helped me review the basic 
   shell commands. I was then taught the basics of Git (version control) and I later applied
   this in creating my repository for the internship. Finally, I was taught the basic structure 
   of emacs and I played around with it, learning some of its commands and functionalities. 
** [2016-05-17 Tue]
   +  Familiarization with web applications and data models. Discrete math
     implementation in said data models. Further functionality of emacs was
     explored.
`  + After learning said principles, I made and edited a document about web
     applications. This reviewed emacs and webapp principles. Then I completed
     the data model for the system that we are designing- the email user
     database.   

** [2016-05-18 Wed]
   + Familiarization with Object Oriented Programming 
   + Creating objects, classes and methods for our application. This was after
     understanding the basics. The test cases were also supposed to be covered,
     which I did not complete.
** [2016-05-19 Thu]
   + Finishing the test cases and objects in the given template, with specific
     focus on the session.
   + All the objects and methods were done. Debugging and testing the test case
     codes were not completed. 
** [2016-05-20 Fri]
   + Test cases and object creation. Familiarization with ORM was also expected
   + The system object was created and subsequent classes were modified to
     include the user and session lists as pertaining to the system. System
     methods were created along with some static methods and their respective
     methods. ORM was not completed. (SQLAlchemy Framework)
** Weekly  Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
* Month of June
* Month of July
